name: deliveryboy_multivendor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.0
  shared_preferences: ^2.0.5
  connectivity: ^3.0.3
  shimmer: ^2.0.0
  flutter_phone_direct_caller: ^2.1.1
#  flutter_webview_plugin: ^0.4.0
  flutter_html: ^2.2.1
  fluttertoast: ^8.0.9
  jaguar_jwt: ^3.0.0
  country_code_picker: ^2.0.2
#  firebase_messaging: ^10.0.5
#  firebase_messaging: ^12.0.3
  firebase_messaging: ^14.1.2
#  flutter_local_notifications: ^8.1.1+1
  flutter_local_notifications: ^9.8.0+1
  path_provider: ^2.0.2
  sms_autofill: ^2.0.1
  firebase_auth: ^4.12.0
  url_launcher: ^6.0.2
  intl: ^0.18.1
  flutter_svg: ^0.22.0
  firebase_core: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides:
  ! modal_bottom_sheet: ^3.0.0-pre

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: opensans
      fonts:
         - asset: assets/font/opensans-regular.ttf
